### ISSUE TITLE
Delta Interval Incorrect?

### ISSUE THREAD

**Issue by GLStephen** [mia-0032/fluent-plugin-stackdriver-monitoring#5]
The Stackdriver API docs indicates that if the type is DELTA then a non-zero interval must be specified. Currently the plugin specifies the same time for both, which is appropriate for a GAUGE type, but not a DELTA type and likely not a CUMULATIVE type either:

```
def create_time_interval(time)
      time_interval = Google::Monitoring::V3::TimeInterval.new
      time_interval.start_time = Google::Protobuf::Timestamp.new seconds: time
      time_interval.end_time = Google::Protobuf::Timestamp.new seconds: time

      time_interval
    end
```

I'm not using this functionality I was just reviewing the code.

Relevant docs:

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeInterval

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#Point

**Comment by mia-0032** [comment]
Sorry for my late replying. I added configuration of time interval. But custom metrics doesn't support `DELTA` type. So I deleted `DELTA` type support.
